# Generated by Django 5.0 on 2025-12-10 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text="Pet's name (if known)", max_length=100, null=True)),
                ('category', models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('OTHER', 'Other')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('description', models.TextField(help_text='Distinctive features, markings, etc.')),
                ('last_seen_location', models.CharField(max_length=200)),
                ('last_seen_date', models.DateField()),
                ('reward_offered', models.DecimalField(blank=True, decimal_places=2, help_text='Reward amount (if any)', max_digits=10, null=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('MISSING', 'Missing'), ('FOUND', 'Found'), ('CLOSED', 'Closed')], default='MISSING', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_date', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_pet_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Missing Pet Report',
                'verbose_name_plural': 'Missing Pet Reports',
                'db_table': 'missing_pets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissingPetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='missing_pets/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('missing_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='missing_pets.missingpet')),
            ],
            options={
                'verbose_name': 'Missing Pet Image',
                'verbose_name_plural': 'Missing Pet Images',
                'db_table': 'missing_pet_images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='missingpet',
            index=models.Index(fields=['category'], name='missing_pet_categor_0d7ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='missingpet',
            index=models.Index(fields=['last_seen_location'], name='missing_pet_last_se_8d3d29_idx'),
        ),
        migrations.AddIndex(
            model_name='missingpet',
            index=models.Index(fields=['status'], name='missing_pet_status_47e306_idx'),
        ),
        migrations.AddIndex(
            model_name='missingpet',
            index=models.Index(fields=['-created_at'], name='missing_pet_created_eca0df_idx'),
        ),
    ]
