# Generated by Django 5.0 on 2025-12-10 05:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('NPR', 'Nepalese Rupee'), ('USD', 'US Dollar')], default='NPR', max_length=3)),
                ('payment_method', models.CharField(choices=[('ESEWA', 'eSewa'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=200, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional message from donor', null=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide donor name from public display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When payment was confirmed', null=True)),
                ('donor', models.ForeignKey(blank=True, help_text='Leave blank for anonymous donations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'donations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_status'], name='donations_payment_245ebc_idx'), models.Index(fields=['payment_method'], name='donations_payment_1afce4_idx'), models.Index(fields=['-created_at'], name='donations_created_95af24_idx')],
            },
        ),
    ]
