# Generated by Django 5.0 on 2025-12-10 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('FEEDBACK', 'Feedback'), ('BUG_REPORT', 'Bug Report'), ('SUGGESTION', 'Suggestion'), ('COMPLAINT', 'Complaint'), ('OTHER', 'Other')], default='FEEDBACK', max_length=15)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to user)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'db_table': 'feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='feedback_status_d7fa3d_idx'), models.Index(fields=['type'], name='feedback_type_0c71a9_idx'), models.Index(fields=['-created_at'], name='feedback_created_d6e06a_idx')],
            },
        ),
    ]
