# Generated by Django 5.0 on 2025-12-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RescueContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of shelter/clinic', max_length=200)),
                ('type', models.CharField(choices=[('SHELTER', 'Shelter'), ('VETERINARIAN', 'Veterinarian')], max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('operating_hours', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Total capacity (for shelters)', null=True)),
                ('specialization', models.CharField(blank=True, help_text='Specialization (for veterinarians)', max_length=200, null=True)),
                ('services', models.TextField(blank=True, help_text='Services offered (for veterinarians)', null=True)),
                ('emergency_service', models.BooleanField(default=False, help_text='24/7 emergency service available')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rescue Contact',
                'verbose_name_plural': 'Rescue Contacts',
                'db_table': 'rescue_contacts',
                'ordering': ['type', 'name'],
                'indexes': [models.Index(fields=['type'], name='rescue_cont_type_f7b536_idx'), models.Index(fields=['city'], name='rescue_cont_city_14dd88_idx'), models.Index(fields=['is_verified'], name='rescue_cont_is_veri_0d2912_idx')],
            },
        ),
    ]
