# Generated by Django 5.0 on 2025-12-10 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog'), ('OTHER', 'Other')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(help_text='Age in months')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=10)),
                ('description', models.TextField()),
                ('health_info', models.TextField(blank=True, help_text='Vaccination, medical history, etc.', null=True)),
                ('location', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ADOPTED', 'Adopted'), ('PENDING', 'Pending'), ('REMOVED', 'Removed')], default='AVAILABLE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adoption_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet Listing',
                'verbose_name_plural': 'Pet Listings',
                'db_table': 'pets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adopt.pet')),
            ],
            options={
                'verbose_name': 'Pet Image',
                'verbose_name_plural': 'Pet Images',
                'db_table': 'pet_images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['category'], name='pets_categor_f5e4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['location'], name='pets_locatio_e90c09_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['status'], name='pets_status_af7f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['-created_at'], name='pets_created_a34369_idx'),
        ),
    ]
